# Generated by Django 5.2.7 on 2025-12-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adminuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
